server:
  ssl:
    enabled: true
    protocol: TLS
    key-store: /DATA/ssl/dev.startuplab.com.pfx
    key-store-password: teamwsslP@ssw0rd
    key-store-type: PKCS12
spring:
  task:
    execution:
      pool:
        max-size: 300
        queue-capacity: 500
      thread-name-prefix: my-exec-
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://115.85.181.186:33306/dev?autoReconnection=true&useUnicode=true&characterResultSets=utf8&useSSL=false
    username: startuplabDB
    password: startuplabDB
    pool-name: db-pool
    maximum-pool-size: 50
    data-source-properties:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
logging:
  level:
    "[com.startuplab]": info
  file:
    name: /DATA/springboot/startuplab/logs/catalina.out
